source: source
destination: site
markdown: rdiscount
pygments: true
permalink: /articles/:categories/:year/:month/:day/:title
url: http://edgerails.info
multiviews: true
sass: false
haml: true
lsi: true
post_defaults:
  layout: default